services:
  db:
    image: pgvector/pgvector:pg17 # for pgvector support
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      FLASK_ENV: development
      FLASK_APP: main.py

    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
