// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { SignupApiAuthSignupPostData, SignupApiAuthSignupPostResponse, LoginApiAuthLoginPostData, LoginApiAuthLoginPostResponse, ReadMeApiUsersMeGetResponse } from './types.gen';

export class AuthService {
    /**
     * Signup
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SignUpResponse Successful Response
     * @throws ApiError
     */
    public static signupApiAuthSignupPost(data: SignupApiAuthSignupPostData): CancelablePromise<SignupApiAuthSignupPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/auth/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Login
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TokenResponse Successful Response
     * @throws ApiError
     */
    public static loginApiAuthLoginPost(data: LoginApiAuthLoginPostData): CancelablePromise<LoginApiAuthLoginPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/auth/login',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Me
     * @returns ReadUser Successful Response
     * @throws ApiError
     */
    public static readMeApiUsersMeGet(): CancelablePromise<ReadMeApiUsersMeGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/users/me'
        });
    }
}