// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type ReadUser = {
    name: string;
    email: string;
    id: string;
    created_at: (string | null);
};

export type SignUpRequest = {
    name: string;
    email: string;
    password: string;
};

export type SignUpResponse = {
    id: string;
    name: string;
    email: string;
};

export type TokenResponse = {
    access_token: string;
    token_type?: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type SignupApiAuthSignupPostData = {
    requestBody: SignUpRequest;
};

export type SignupApiAuthSignupPostResponse = (SignUpResponse);

export type LoginApiAuthLoginPostData = {
    requestBody: LoginRequest;
};

export type LoginApiAuthLoginPostResponse = (TokenResponse);

export type ReadMeApiUsersMeGetResponse = (ReadUser);