"""add documents table with embeddings

Revision ID: 779df091e520
Revises: 60c0cf9b1fd9
Create Date: 2025-08-15 23:00:14.070146

"""

from alembic import op
import sqlalchemy as sa
from app.chat.models import Vector

# revision identifiers, used by Alembic.
revision = "779df091e520"
down_revision = "60c0cf9b1fd9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("embedding", Vector(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    # ### end Alembic commands ###
