"""changed documents table to movies

Revision ID: f9595e5a9a96
Revises: 779df091e520
Create Date: 2025-08-16 01:48:02.612704

"""

from alembic import op
import sqlalchemy as sa
from app.chat.models import Vector


# revision identifiers, used by Alembic.
revision = "f9595e5a9a96"
down_revision = "779df091e520"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("embedding", Vector(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("documents")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("documents_pkey")),
    )
    op.drop_table("movies")
    # ### end Alembic commands ###
