// This file is auto-generated by @hey-api/openapi-ts

export type app__models__Message = {
    role?: Role;
    content: string;
    status?: Status;
    id?: string;
    owner_id: string;
    session_id: string;
};

export type app__schemas__Utils__Message = {
    message: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MessageDetail = {
    role?: Role;
    content: string;
    status?: Status;
    id: string;
};

export type NewMessage = {
    role?: Role;
    content: string;
    status?: Status;
    model_name: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NewSession = {
    title: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Role = 'user' | 'assistant' | 'system';

export type SessionDetail = {
    title: string;
    id: string;
    messages: Array<MessageDetail>;
};

export type SessionList = {
    sessions: Array<SessionSimple>;
};

export type SessionSimple = {
    title: string;
    id: string;
};

export type Status = 'complete' | 'failure' | 'streaming';

export type StreamResponseBody = {
    model_name: string;
    message_id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UpdateSession = {
    title: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (app__models__Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (app__models__Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SessionGetSessionsResponse = (SessionList);

export type SessionNewSessionData = {
    requestBody: NewSession;
};

export type SessionNewSessionResponse = (string);

export type SessionGetSessionData = {
    sessionId: string;
};

export type SessionGetSessionResponse = (SessionDetail);

export type SessionDeleteSessionData = {
    sessionId: string;
};

export type SessionDeleteSessionResponse = (app__schemas__Utils__Message);

export type SessionRenameSessionData = {
    requestBody: UpdateSession;
    sessionId: string;
};

export type SessionRenameSessionResponse = (app__schemas__Utils__Message);

export type SessionAddMessageData = {
    requestBody: NewMessage;
    sessionId: string;
};

export type SessionAddMessageResponse = (string);

export type SessionChatData = {
    requestBody: StreamResponseBody;
    sessionId: string;
};

export type SessionChatResponse = (app__models__Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (app__models__Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (app__models__Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (app__models__Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (app__models__Message);

export type UtilsHealthCheckResponse = (boolean);